#!/usr/bin/env bash

# Adds a new test case
#
# Usage: add [n]
#
# n - number of test cases
#     default: 1

# Number of new test cases
n=${1:-1}

# Get the last test case
file=$(tests/count)

# For each new test case, open editor
while [[ $n -gt 0 ]] ;
do
	((++file))
	$(tests/func edit "\"tests/cases/input/$file\"")
	((--n))
done
