#!/usr/bin/env bash

# Compares input and output test cases
#
# Usage: compare tester [tc1 [tc2 ...] ] (0)
#        compare tester {tc1..tcn}       (1)
#        compare tester
#
# (0) List of test cases
# (1) Range of test cases
# (2) Last tast case

# Tester
tester=$1
shift

# Initialize fail counter to 0
failcnt=0

# Colours for printing
YELLOW='\033[0;33m'
NOCOLOR='\033[0m'

# Test cases
tcs=${@:-$(tests/count "$tester")}

# Directories
inputdir=tests/cases/$tester/input
outputdir=tests/cases/$tester/output
candidatesdir=bin/candidates/$tester

# For every test case...
for i in $tcs; do
	if [[ -f "$outputdir/$i" ]] ; then
		# Check if there an output...
		$(tests/func edit "\"$inputdir/$i\"" "\"$outputdir/$i\"")
	elif [[ -f "$candidatesdir/$i" ]] ; then
		# ...or a candidate...
		$(tests/func edit "\"$inputdir/$i\"" "\"$candidatesdir/$i\"")
		# Ask if candidate should be approved...
		printf $YELLOW"Should candidate #$i be approved (y/n)? "$NOCOLOR
		read yn
		case $yn in
			[Yy]* ) cp $candidatesdir/$i output;;
			[Nn]* ) exit;;
			* ) echo "Invalid input. Assumed 'n'."
		esac
	else
		# ...if not, print an error message...
		echo "Could not find output for test #$i..."
		# ...and increase the fail counter.
		((++failcnt))
	fi
done

# Exit with the fail count
exit $failcnt
