#!/bin/bash

# Edits a test case
#
# Usage: edit [tc]
#
# tc - test case number
#      default: last

# Get script directory
sd=$(dirname -- "$(readlink -f -- "$BASH_SOURCE")")

# Get test case number
tc=${1:-$($sd/count)}

# Search through list of test cases
for file in $($sd/list); do
	# If it matches one of them...
	if [[ $file == $tc ]] ; then
		# ...open test case or...
		$($sd/func EDIT "\"$sd/cases/input/$file\"")
		exit 0
	fi
done 

# ...notify that test case don't exist
echo "Test case $1 doesn't exist"
exit 1
