#!/usr/bin/env bash

# Execute lua function
#
# Usage: func [args...]
#
# func - function name
# args... - function arguments

# Function name
func=$1
shift

# Joining function
function join { local IFS="$1"; shift; echo "$*"; }

# Call function
tests/eval "print($func($(join , "$@")))"
