#!/usr/bin/env bash

# Lists all test cases
#
# Usage: list tester

# Tester
tester=$1
shift

# Input directory
inputdir=tests/cases/$tester/input

# Get new test case name
file=1
while [[ -f "$inputdir/$file" ]] ;
do
	echo "$file"
	((++file))
done
