#!/usr/bin/env bash

# Run tests
#
# Usage: run tester tester_dir

# Tester application
tester=$1
shift

# Tester application path
testerpath=$1/$tester
shift

# logdir is the directory where logs are
# going to be saved
logdir=bin/tests

# Make logdir if nonexistent
mkdir -p $logdir

# tmpdir is the directory where all the
# outputs will be written to so that
# they can be compared with the expected
# outputs
tmpdir=$(mktemp -d)

# failedcnt is the number of tests that
# have failed
failedcnt=0

# skippedcnt is the number of tests that
# have been skipped
skippedcnt=0

# colours useful for printing
LGREEN='\033[1;32m'
LRED='\033[1;31m'
YELLOW='\033[0;33m'
NOCOLOR='\033[0m'

inputdir=tests/cases/$tester/input
outputdir=tests/cases/$tester/output

printf "[ TEST ] Testing $LGREEN%s$NOCOLOR\n" "$tester"

# For every file in cases/input ...
for file in $(tests/list "$tester"); do

	# Notify that test will be run...
	printf "[ TEST ] Running test #%s... " "$file"

	# Run test, saving the output in the temporary directory
	cat $inputdir/$file | $testerpath > $tmpdir/$file 2>&1

	if [[ -f $outputdir/$file ]] ; then
		# Compare the expected and obtained outputs and
		# redirect the diff analysis to the log directory
		if  diff $tmpdir/$file $outputdir/$file > $logdir/$file ; then
			printf $LGREEN"PASSED$NOCOLOR\n"
		else
			printf $LRED"FAILED$NOCOLOR\n"
            echo "Diff result:"
            cat $logdir/$file

			# Increase the count of failed tests
			((++failedcnt))
		fi
	else
		# Skip test case because output is missing 
		printf $YELLOW"SKIPPED"$NOCOLOR" (missing output)\n"

		((++skippedcnt))
	fi

done

# Remove the temporary directory
rm -rf $tmpdir

# Check if any tests failed and print an appropriate
# message to summarize the test results
if [ $failedcnt -eq 0 ] ; then
	printf "[ TEST ] "$LGREEN"All $(tests/count "$tester") tests passed"
else
	printf "[ TEST ] "$LRED"$failedcnt test(s) failed"
fi
printf $NOCOLOR"\n"

# Check if any tests were skipped and print an appopriate
# message to warn the user
if [ $skippedcnt -ne 0 ] ; then
	printf "[ TEST ] "$YELLOW"$skippedcnt test(s) skipped"
	printf $NOCOLOR"\n"
fi

# Exit the script with 0 if no tests failed (i.e. success)
# or else, if at least one failed (i.e. failed)
exit $failedcnt
