#!/usr/bin/env bash

# Obtains configuration variable value
#
# Usage: var name [default]
#
# name - variable name
# default - default variable value
#           default: empty string

# Print global variable or default value if nil
tests/eval "if $1 ~= nil then print($1) else print($2) end"
