name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        Config: [Release, Debug]
    steps:
    - uses: actions/checkout@v2

    - name: Setup
      run: |
        mkdir build_${{ matrix.Config }}
        cd build_${{ matrix.Config }}
        cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.Config }}
    
    - name: Compile
      working-directory: build_${{ matrix.Config }}
      run: |
        cmake --build . --config ${{ matrix.Config }}

    - name: Test
      working-directory: build_${{ matrix.Config }}
      run: |
        ctest -V -C ${{ matrix.Config }}
