name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        CONFIG: [Release, Debug]
    steps:
    - uses: actions/checkout@v2

    - name: Setup
      run: |
        mkdir build_$CONFIG
        cd build_$CONFIG
        cmake .. -DCMAKE_BUILD_TYPE=$CONFIG
    
    - name: Compile
      working-directory: build_$CONFIG
      run: |
        cmake --build . --config $CONFIG

    - name: Test
      working-directory: build_$CONFIG
      run: |
        ctest -V -C $CONFIG
